news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links : '.bsg-Macrogaleria_Titulo a, .titulo a'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links : 'header h2.c_t a'

    